# Generated by Django 2.2.7 on 2020-06-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='m_Efficacy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='m_Side_Effect',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
